### ISSUE TITLE
How do you delete a node?

### ISSUE THREAD

**Issue by b1ek** [jbeder/yaml-cpp#1088]
So i've got a document that should contain only necessary nodes, for example:
```yml
name: John Doe
age: 21
note: A cool guy
some_other_shit_to_be_removed_automatically: asbdsvahysfvdgssadgsaj
```
I looked all over the documentation but found nothing. I thought of setting that node to zero value, but it will still remain like this:
```yml
name: John Doe
age: 21
note: A cool guy
some_other_shit_to_be_removed_automatically: 
```

**Comment by b1ek** [comment]
I just found out you can remove a node using `YAML::Node.remove("smth")`.
This should be added to wiki

**Comment by xinthose** [comment]
If I want to remove the `routes` node from `eth1`, do it like this:

```yaml
network:
	ethernets:
		eth0:
			addresses:
			- 192.168.2.2/24
			dhcp4: false
			dhcp6: false
			match:
				macaddress: 00:e0:97:1b:56:02
			nameservers:
				addresses:
				- 8.8.8.8
			routes:
				- to: default
				via: 192.168.2.1
			set-name: eth0
		eth1:
			addresses:
			- 10.0.0.2/24
			dhcp4: false
			dhcp6: false
			match:
				macaddress: 00:e0:97:1b:56:03
			nameservers:
				addresses: []
			set-name: eth1
	renderer: NetworkManager
	version: 2
```

```cpp
YAML::Node config = YAML::LoadFile("/etc/netplan/01-network-manager-all.yaml");

// wrong, does not work
config.remove(config["network"]["ethernets"]["eth1"]["routes"]);

// correct
config["network"]["ethernets"]["eth1"].remove("routes");
```
