### ISSUE TITLE
Having issue when reading string parameters

### ISSUE THREAD

**Issue by ulassbin** [jbeder/yaml-cpp#1135]
I am having issues with YAML::Load(file_name) command. String parameters are being converted to something different
```
For example 
- type: "shelf" 
becomes 
- type: !<!> shelf

```
I am reading the yaml file as follows:
```   
    YAML::Node config = YAML::LoadFile("/home/ulas/local.yaml");
    YAML::Emitter emit;
    emit << config;
    std::cout << "Initial \n"<<emit.c_str()<<std::endl;`
``` 
My yaml  file looks like this
```
item_manager:
  active_items:
    - type: "shelf"
    - type: "drawer"
      params:
        front_drawer:
          color: 1.0                  
    - type: "window"
      params:
        window:
          height: 1.0           
```  

The output becomes
``` 
Initial 
item_manager:
  active_items:
    - type: !<!> shelf
    - params:
        front_drawer:
          color: 1.0
      type: !<!> drawer
    - type: !<!> window
      params:
        window:
          height: 1.0
```
