### ISSUE TITLE
How to preserve Double Quotes for explicit string values using Emitter?

### ISSUE THREAD

**Issue by Levi-Armstrong** [jbeder/yaml-cpp#1199]
It looks like there is no way to reproduce the following yaml using the Emitter. I would assume that if this can be parsed then there should be a way to reproduce the exact contents using the Emitter. I tried calling `SetStringFormat(YAML::DoubleQuoted)` but this also put double quotes on the keys which is not the same if you are trying to leverage the tag `"!'` to know if it is an explicit string or not. 

``` yaml
config:
  boolean: true
  string: "input_data"
  int: 100
  float: 100.5;
```

Using `SetStringFormat(YAML::DoubleQuoted)` which does not produce the same.

``` yaml
"config":
  "boolean": "true"
  "string": "input_data"
  "int": "100"
  "float": "100.5"
```
