### ISSUE TITLE
yaml fail to parse nodes, doesn't give clue why

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jbeder/yaml-cpp#157]
```
What steps will reproduce the problem?
1. use this yaml, without the ------- and ..... at start and end.

-------------

a:
    as:
        ad:
            ab:
            dsfdsdas:
            fggww:
            badaba:
            dsdsa:
            fdssd:
            fdssada:
        ad5:
            dada:
            dudu:
                gaga:
                budu:
        ad6:
d:
    as:
        ad:
            ab:
            dsfdsdas:
            fggww:
            badaba:
            dsdsa:
            fdssd:
            fdssada:
        ad5:
            dada:
            dudu:
                gaga:
                budu:
        ad6:
fds:
    as:
        ad:
            ab:
            dsfdsdas:
            fggww:
            badaba:
            dsdsa:
            fdssd:
            fdssada:
        ad5:
            dada:
            dudu:
                gaga:
                budu:
        ad6:
fdsa:
    as:
        ad:
            ab:
            dsfdsdas:
            fggww:
            badaba:
            dsdsa:
            fdssd:
            fdssada:
        ad5:
            dada:
            dudu:
                gaga:
                budu:
        ad6:
sa:
    as:
        ad:
            ab:
            dsfdsdas:
            fggww:
            badaba:
            dsdsa:
            fdssd:
            fdssada:
        ad5:
            dada:
            dudu:
                gaga:
                budu:
        ad6:
jhf:
    as:
        ad:
            ab:
            dsfdsdas:
            fggww:
            badaba:
            dsdsa:
            fdssd:
            fdssada:
        ad5:
            dada:
            dudu:
                gaga:
                budu:
        ad6:
ddd:
    as:
        ad:
            ab:
            dsfdsdas:
            fggww:
            badaba:
            dsdsa:
            fdssd:
            fdssada:
        ad5:
            dada:
            dudu:
                gaga:
                budu:
        ad6:
dd222d:
    as:
        ad:
            ab:
            dsfdsdas:
            fggww:
            badaba:
            dsdsa:
            fdssd:
            fdssada:
        ad5:
            dada:
            dudu:
                gaga:
                budu:
        ad6:
dd4444d:
    as:
        ad:
            ab:
            dsfdsdas:
            fggww:
            badaba:
            dsdsa:
            fdssd:
            fdssada:
        ad5:
            dada:
            dudu:
                gaga:
                budu:
        ad6:
d555dd:
    as:
        ad:
            ab:
            dsfdsdas:
            fggww:
            badaba:
            dsdsa:
            fdssd:
            fdssada:
        ad5:
            dada:
            dudu:
                gaga:
                budu:
        ad6:
dd777d:
    as:
        ad:
            ab:
            dsfdsdas:
            fggww:
            badaba:
            dsdsa:
            fdssd:
            fdssada:
        ad5:
            dada:
            dudu:
                gaga:
                budu:
        ad6:
ddd99:
    as:
        ad:
            ab:
            dsfdsdas:
            fggww:
            badaba:
            dsdsa:
            fdssd:
            fdssada:
        ad5:
            dada:
            dudu:
                gaga:
                budu:
        ad6:


.........................

2.

use this code:
    YAML::Parser parser(ifstream("test2.yml"));
    //YAML::Parser parser(ifstream("items9.yml"));
    YAML::Node doc;
    if(! parser.GetNextDocument(doc)) exit(0xbadf00d);

    vector<string> string_vector;// = getkeys(doc);
    for(auto it = doc.begin(); it != doc.end(); ++it)
    {
        string s;
        it.first() >> s;
        string_vector.push_back(s);
    }


    for(auto it = string_vector.begin(); it != string_vector.end(); ++it)
        cout << *it << "\n";


3. it doesn't get all nodes, I don't know why, it still is valid yaml


using 0.3.0, windows xp, visual C++ 10

I don't think it's caused by hash key collision, because the data I use in my 
app are common english words, and I have the same issue.
```

Original issue reported on code.google.com by `ezjonas` on 26 Mar 2012 at 10:56
