### ISSUE TITLE
map type didn't support same key

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jbeder/yaml-cpp#243]
```
Sample: 
m_TexEnvs:
      data:
        first:
          name: _MainTex
        second:
          m_Texture: {fileID: 2800000, guid: 8a75e78ce03d6bf4aa7ab9b759c2ca32, type: 3}
          m_Scale: {x: 1, y: 1}
          m_Offset: {x: 0, y: 0}
      data:
        first:
          name: _BumpMap
        second:
          m_Texture: {fileID: 2800000, guid: 0b178db3c9e8755499da46a52e53ce76, type: 3}
          m_Scale: {x: 1, y: 1}
          m_Offset: {x: 0, y: 0}
      data:
        first:
          name: _Mask
        second:
          m_Texture: {fileID: 0}
          m_Scale: {x: 1, y: 1}
          m_Offset: {x: 0, y: 0}

when use yaml-cpp to m_TexEnvs , it can only store one "data" key-value pair
'cause there is a "operator<"function for (const node*)  in line 18 at node.cpp 

```

Original issue reported on code.google.com by `ruzhenc...@gmail.com` on 2 Apr 2014 at 9:51
