### ISSUE TITLE
anchors/aliases in map keys do not work

### ISSUE THREAD

**Issue by mrshrdlu** [jbeder/yaml-cpp#312]
The following YAML

``` yaml
first:
  &baz foo: bar
second:
  *baz: bar
```

should be equivalent to

``` yaml
first: 
  foo: bar
second: 
  foo: bar
```

However, the following code

``` c++
#include <yaml-cpp/yaml.h>
#include <iostream>
int main() {
  YAML::Node doc = YAML::Load(
    "first:\n"
    "  &baz foo: bar\n"
    "second:\n"
    "  *baz: bar\n"
    );
  std::cout << doc["first"] << std::endl;
  return 0;
}
```

produces the error

```
terminate called after throwing an instance of 'YAML::ParserException'
  what():  yaml-cpp: error at line 4, column 3: the referenced anchor is not defined
Aborted (core dumped)
```

I am using yaml-cpp 0.5.1 on Ubuntu 14.04.
EDIT: issue also confirmed with yaml-cpp 0.5.2.
