### ISSUE TITLE
Using <<: to insert anchored map produces incorrect results

### ISSUE THREAD

**Issue by rdeits** [jbeder/yaml-cpp#353]
For example, using the yaml file described in this SO answer: http://stackoverflow.com/a/9197237 

```yaml
Defaults: &defaults
  Company: foo
  Item: 123

Computer:
  <<: *defaults
  Price: 3000
```

in python, using the `yaml` package, I get (correctly): 

```
>>> config = yaml.load(open('Base.yaml'))
>>> print(config)
{'Computer': {'Item': 123, 'Price': 3000, 'Company': 'foo'}, 'Defaults': {'Item': 123, 'Company': 'foo'}}
```

(note that the Defaults map has been merged into the Computer map). 

but using `yaml-cpp`, the `<<` is interpreted as a map key, rather than inserting the contents of that map, so `config["Computer"]` gives: 

```
<<:
  Item: 123
  Company: foo
Price: 3000
```
