### ISSUE TITLE
nesting a map-seq-map with an empty value (appears character ?)

### ISSUE THREAD

**Issue by joseAndresGomezTovar** [jbeder/yaml-cpp#416]
I want to emit a yaml output like this

```
- id: 0
  default: 1
  name: Desktop
  desc: Initial Desktop
  ventanas:
    - id: 1
      top: 0
      left: 0
      width: 400
      height: 450
      source: 
    - id: 2
      top: 0
      left: 400
      width: 400
      height: 450
      source: 
```

using a operator << like this

```
void operator << (YAML::Emitter &out, const stDesktop_t &ii) {
      
      out << YAML::BeginSeq;
      out << YAML::BeginMap;
      out << YAML::Key << "id" << YAML::Value << ii.m_iId;
      out << YAML::Key << "default" << YAML::Value << ii.m_iDefault;
      out << YAML::Key << "name" << YAML::Value << ii.m_sName;
      out << YAML::Key << "desc" << YAML::Value << ii.m_sDesc;
      out << YAML::Key << "ventanas";

      for (unsigned i = 0; i < ii.m_cVentana.size(); ++i) {
         //out << YAML::Value << YAML::BeginSeq;
         out << YAML::BeginSeq;
         out << YAML::BeginMap; 
         out << YAML::Key << "id" << YAML::Value << ii.m_cVentana[i].m_iId;
         out << YAML::Key << "top" << YAML::Value << ii.m_cVentana[i].m_iTop;
         out << YAML::Key << "left" << YAML::Value << ii.m_cVentana[i].m_iLeft;
         out << YAML::Key << "width" << YAML::Value << ii.m_cVentana[i].m_iWidth;
         out << YAML::Key << "height" << YAML::Value << ii.m_cVentana[i].m_iHeight;
         out << YAML::Key << "source" << YAML::Value << "";
         out << YAML::EndMap;
         out << YAML::EndSeq;
      }
      out << YAML::EndMap;
      out << YAML::EndSeq;
   };

```
the out is like this... **what can I do? _thank you in advance_**

```
- id: 0
  default: 1
  name: Desktop
  desc: Initial Desktop
  ventanas:
    - id: 1
      top: 0
      left: 0
      width: 400
      height: 450
      source: ""
  ? - id: 2
      top: 0
      left: 400
      width: 400
      height: 450
      source: ""
  : - id: 3
      top: 450
      left: 0
      width: 1600
      height: 450
      source: ""
  ? - id: 4
      top: 0
      left: 800
      width: 800
      height: 450
      source: ""
```
