### ISSUE TITLE
First key of map of sequence is not properly parsed

### ISSUE THREAD

**Issue by devnoname120** [jbeder/yaml-cpp#464]
Here is my YAML:
```YAML
homebrews:
  vita:
    - name: "PSP2048"
      author: dots-tb
    - name: "PSVident"
      author: Freakler
```

Here is the code that I use to parse it:
```C
YAML::node db = /* ... */;
YAML::node hombrews = db["homebrews"];
YAML::node vita = db["vita"];

for (auto it=vita.begin(); it!=vita.end(); ++it) {
    YAML::Node cHb = *it;
    std::string nme = cHb["author"].as<std::string>(); // Works properly
    nme = cHb["name"].as<std::string>(); // Throws an incorrect conversion exception because the node has a null type
}
```

Now if I change my YAML to the following, I don't have an exception anymore and the string holds the correct value.
```YAML

homebrews:
  vita:
    -
      name: "PSP2048"
      author: dots-tb
    -
      name: "PSVident"
      author: Freakler
```

Both YAML are equivalent and should be parsed properly. Representations: [first](http://yaml-online-parser.appspot.com/?yaml=homebrews%3A%0A++vita%3A%0A++++-+name%3A+%22PSP2048%22%0A++++++author%3A+dots-tb%0A++++-+name%3A+%22PSVident%22%0A++++++author%3A+Freakler&type=json), [second](http://yaml-online-parser.appspot.com/?yaml=homebrews%3A%0A++vita%3A%0A++++-%0A++++++name%3A+%22PSP2048%22%0A++++++author%3A+dots-tb%0A++++-%0A++++++name%3A+%22PSVident%22%0A++++++author%3A+Freakler&type=json).

Note: I'm using yaml-cpp on the Vita (ARM Cortex-A9 CPU), I did not try it on a desktop architecture.
