### ISSUE TITLE
Merge 2 YAML::Node

### ISSUE THREAD

**Issue by tgy** [jbeder/yaml-cpp#497]
I use YAML for configuring a software. It looks like this

```yaml
foo: bar
barafoo:
  footabar: foofoofoo
  tabafoorab: batabataba
fabfab: 23
```

I hard-code default values for all of these settings in a default `YAML::Node` and retrieve user-specified settings from an optional file in `/etc/foo/config.yml`.

Say `/etc/foo/config.yml` contains the following

```yaml
barafoo:
  tabafoorab: heyhey
fabfab: 42
```

I would like to use all the settings from the default `YAML::Node` (hardcoded in the software) but override those settings if they have different values in `/etc/foo/config.yml`.

In a sense, I would like to merge 2 `YAML::Node`, taking all keys from the first one and giving priority to keys in the second one.

Is there something already implemented in `yaml-cpp` or do I need to write my own function to do that?
