### ISSUE TITLE
sequence as map key throws exception when checking  key.IsSequence(), but the key can get parsed successfully.

### ISSUE THREAD

**Issue by tankiJong** [jbeder/yaml-cpp#581]
Since this is a specific case issue, I will demonstrate my case for reference.
This is the file I was trying to parse:
```yaml
name: material/specular
properties:
  PhysicalAttr: {
    [SPECULAR_AMOUNT, float]: 3.f
    [SPECULAR_POWER, float]: [10.f], 
  }
  TexDiffuse: [0, Data/Images/couch/couch_diffuse.png, LINEAR]
  gTexNormal: [1, Data/Images/couch/couch_normal.png, LINEAR]

shader:
  name: shader/default_lit
```

I was trying to say something like:
```cpp
for(auto& attr: node["properties"]["PhysicalAttr"]) EXPECTS(attr.first.IsSequence())
                                                                        ^~~~~~~~
```
Exception racised at Impl.h: **NodeType::value Node::Type()** Line 79.

But, be aware that whether I call IsSequence() will not affect the data parsing, which means directly parsing the data(the following code) will always be successful.
```cpp
  std::string name = attr.first[0].as<std::string>();
  std::string type = attr.first[1].as<std::string>();
```

Apparently, when parsing the node, the key part `[SPECULAR_AMOUNT, float]` is marked as invalid at some point. I will be very glad to try fixing this if someone can provide me some information about the node life cycle, in terms of the timing when the valid flag get set.

Thank you very much :D
