### ISSUE TITLE
Anchor/Alias crashs on accessing not overridden key/value

### ISSUE THREAD

**Issue by hofbi** [jbeder/yaml-cpp#617]
My yaml file has the following structure

```yaml
a_root: &root_anchor
  key1: value1
  key2: value2
b_child:
  <<: *root_anchor
  key2: value2_override
```
If I evaluate this file with [yamllint.com](http://www.yamllint.com/) or [pyyaml](https://pyyaml.org/) this results into
```yaml
a_root: 
  key1: value1
  key2: value2
b_child: 
  key1: value1
  key2: value2_override
```
But If I try to access the value of `[b_child][key1]` this result in a crash as `key1` does not exit for `b_child`

This issue could be related to #312 and #110
