### ISSUE TITLE
Leak memory when parsing nested structure

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jbeder/yaml-cpp#62]
```
with the yaml like this:
drugInfo:
  drug:
    id: 1
    half_life: 1
    epsilon_daily_effect: 0.8
    percent_kill_perday: 0.9999
    mutation_probability: 0.0005
    k: 4
    ResistantCostMulitipleInfectionLenght: 0.05
    ResistantCostMultipleInfection: 0.03
  drug:
    id: 2
    half_life: 1
    epsilon_daily_effect: 0.8
    percent_kill_perday: 0.9999
    mutation_probability: 0.0005
    k: 4
    ResistantCostMulitipleInfectionLenght: 0.05
    ResistantCostMultipleInfection: 0.03

It will cause a leak memory
```

Original issue reported on code.google.com by `merli...@gmail.com` on 21 Jan 2010 at 8:13
