### ISSUE TITLE
BlockSeq indents issue

### ISSUE THREAD

**Issue by dannypike** [jbeder/yaml-cpp#631]
I'm new to this game, so apologies if this is wrong, but it seems to me that yaml-cpp is adding too many indents on block sequences. This is the "recommended" format for a typical block sequence:

```
map1:
- map2:
    value2_1: 0
    value2_2: 1
- map3:
    value3_1: 0
    value3_2: 1
```

whereas yaml-cpp indents the sequence unnecessarily:

```
map1:
  - map2:
      value2_1: 0
      value2_2: 1
 - map3:
      value3_1: 0
      value3_2: 1
```

I realise it's a small problem, but the size can add up when there are hundreds of thousands of lines.

I think that the problem lies in emitter.cpp at line 354 in 774f25800e6f19f4b927023c85d1389af322da5e:

```
void Emitter::BlockSeqPrepareNode(EmitterNodeType::value child) {
  const std::size_t curIndent = m_pState->CurIndent();
  const std::size_t nextIndent = curIndent + m_pState->CurGroupIndent();

  if (child == EmitterNodeType::NoType)
    return;

  if (!m_pState->HasBegunContent()) {
    if (m_pState->CurGroupChildCount() > 0 || m_stream.comment()) {
      m_stream << "\n";
    }
    m_stream << IndentTo(curIndent);    <=== should this be something like max(0, curIndent - 1)?
    m_stream << "-";
  }
```

but I can't build yaml-cpp under Windows/VS2017 in order to test it and submit a PR (I get a lot of errors about unknown overrides). Can you fix it and update the vcpkg for me?

Many thanks,

Dan
