### ISSUE TITLE
Too permissive of incorrectly written repeated fields?

### ISSUE THREAD

**Issue by fredlas** [jbeder/yaml-cpp#651]
Disclaimer: I'm barely familiar with YAML at all, so it may very well be that this is just how it has to be.

I'm working on something that parses YAML, to ultimately turn it into a protobuf. That protobuf has a repeated field named 'clusters'. Because I was unfamiliar with YAML, and didn't have any examples of YAML sequences with more than one item at hand, I guessed that it should look like:

```
static_resources:
  clusters:
    name: cluster_0
    hosts:
      socket_address:
        address: 127.0.0.1
        port_value: 0
  clusters:
    name: my_cds_cluster
    hosts:
      socket_address:
        address: 127.0.0.1
        port_value: 0
```

That got parsed without complaint, but with only the second 'clusters' item present. I would have appreciated for it to have instead failed to parse! It took me a while to start questioning assumptions as fundamental as "the YAML config parser didn't silently ignore anything I gave it."

Also, could this perhaps be related to #321 ?
