### ISSUE TITLE
YAML::Load format is inconsistent with file

### ISSUE THREAD

**Issue by MeeSong** [jbeder/yaml-cpp#790]
Hi, First thanks to the authors.

Code:
```cpp
auto vDoc = YAML::LoadFile("test.yaml");
std::cout << YAML::Dump(vDoc) << std::endl;
```

Document content:
```yaml
install:
    globals:
        locale: "en_US"
        region: "NA"
    lifecycle:
        enable_run_in_background: false
```
Output:
```yaml
install:
  globals:
    locale: en_US
    region: NA
  lifecycle:
    enable_run_in_background: false
```

Where are the double quotes?

I want to modify the file, but the format is inconsistent.

I tried this:
```cpp
YAML::Emitter vEmitter;
vEmitter.SetIndent(4);
vEmitter.SetStringFormat(YAML::DoubleQuoted);

vEmitter << YAML::LoadFile(c_file);
std::cout << vEmitter.c_str() << std::endl;
```

But, Output:
```yaml
"install":
    "globals":
        "locale": "en_US"
        "region": "NA"
    "lifecycle":
        "enable_run_in_background": "false"
```

Key and Boolean do not require double quotes!
