### ISSUE TITLE
jbeder/yaml-cpp master allows for duplicate keys without an error?

### ISSUE THREAD

**Issue by spdomin** [jbeder/yaml-cpp#826]
Greetings,

Our open-source CFD code base https://github.com/NaluCFD/Nalu uses Yaml 0.6.2 (see https://nalu.readthedocs.io/en/latest/source/user/build_manually.html for our build instructions).

Recently, a user provided an input file that included multiple keys for "taget_name":

```
    material_properties:

          target_name: Unspecified-2-HEX 
          constant_specification:
              universal_gas_constant: 8314.4621

          target_name: Unspecified-3-HEX 
          constant_specification:
              universal_gas_constant: 8314.4621

```

I believe that I have learned that the YAML standard > 1.0 should catch this error. As such, I just updated our version of Yaml (de8253fcb075c049c4ad1c466c504bf3cf022f45) however, this version also allows for this above syntax. 

Finally, if I cut and paste the above to an online YAML checker, see for example, https://onlineyamltools.com/validate-yaml, I see a clear error (attached image).

Any help on this matter would be most appreciated.

![yamlError](https://user-images.githubusercontent.com/8699324/74775313-ac50e500-5252-11ea-91af-f6d0a0c41b66.png)
