### ISSUE TITLE
Segementation Fault parsing yaml file``

### ISSUE THREAD

**Issue by suab321321** [jbeder/yaml-cpp#842]
OS - ubuntu 18.04
yaml-cpp -  0.6.x
@jbeder 
I get this segmentation fault when I parse my `.yaml` file

![Screenshot from 2020-04-01 00-33-36](https://user-images.githubusercontent.com/52123334/78071723-98ed7980-73bb-11ea-80f6-8dfe2d166505.png)

**Comment by suab321321** [comment]
@jbeder

**Comment by suab321321** [comment]
my yaml file 
```
disabled: false
reporter:
    logSpans: true
sampler:
  type: probabilistic
  param: 1
```
