### ISSUE TITLE
Add emitting of json

### ISSUE THREAD

**Issue by L0ric0** [jbeder/yaml-cpp#941]
Add emition of json that keaps the types of the build in onjects.

I know that it is possible to emmit valid json with something like: `emitter << YAML::DoubleQuoted << YAML::Flow << ...` but that converts all fields to strings when parsed to json so this:
```
listeners:
  - address: 127.0.0.1
    port: 8080
    https: false
```
is converted to: 
```
{"listeners": [{"address": "127.0.0.1", "port": "8080", "https": "false"}]}
```
which certainly is valid json but the `port` and `https` fields have changed their type from `int/bool` to `string` which is not desired.
