### ISSUE TITLE
How does yaml-cpp read multiple objects that belong to a same class/struct?

### ISSUE THREAD

**Issue by AIBluefisher** [jbeder/yaml-cpp#952]
Hi, I got a problem in reading multiple objects that are the same struct, and I have no idea of how to use yaml-cpp to read them from yaml file. The configure file is like below:
```yaml
cameras:
- camera:
    label: cam0
    id: 54812562fa109c40fe90b29a59dd7798
    line-delay-nanoseconds: 0
    image_height: 480
    image_width: 752
    type: pinhole
    intrinsics:
      cols: 1
      rows: 4
      data: [458.6548807207614, 457.2966964634893, 367.2158039615726, 248.37534060980727]
    distortion:
      type: radial-tangential
      parameters:
        cols: 1
        rows: 4
        data: [-0.28340811217029355, 0.07395907389290132, 0.00019359502856909603,
    1.7618711454538528e-05]
  T_B_C:
    cols: 4
    rows: 4
    data: [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
           0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
          -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
           0.0, 0.0, 0.0, 1.0]
- camera:
    label: cam1
    id: 54812562fa109c40fe90b29a59dd7723
    line-delay-nanoseconds: 0
    image_height: 480
    image_width: 752
    type: pinhole

    intrinsics:
      cols: 1
      rows: 4
      data: [457.5874266035361, 456.13442556023665, 379.9994465203525, 255.2381853862733]
    distortion:
      type: radial-tangential
      parameters:
        cols: 1
        rows: 4
        data: [-0.283683654496, 0.0745128430929, -0.000104738949098, -3.55590700274e-05]
  T_B_C:
    cols: 4
    rows: 4
    data: [0.0125552670891, -0.999755099723, 0.0182237714554, -0.0198435579556,
           0.999598781151, 0.0130119051815, 0.0251588363115, 0.0453689425024,
          -0.0253898008918, 0.0179005838253, 0.999517347078, 0.00786212447038,
           0.0, 0.0, 0.0, 1.0]
```
I have two cameras, so how can I read it by yaml-cpp?
